public with sharing class csaLaserProMappingConstants {
  public static final String PROPERTY_INSTALLEDKEY = 'nCino_LaserPro_Mapping';
  public static final String PROPERTY_INSTALLEDVALUE = 'true';
  public static final String PROERPTY_CATEGORY = 'CSA LaserPro Mapping';

  public static final String FIELD_MAP_PROPERTY_NAME = 'CSA LaserPro Mapping';

  public static final String LASERPRO_ENTITY_DIVIDER = '_';
  public static final String LASERPRO_BLANK_DATA = '';
  public static final String LASERPRO_DATA_DIVIDER = '|';
  public static final String LASERPRO_LINEBREAK = '\n';
}