{
  "totalSize": 1,
  "done": true,
  "records": [
    {
      "attributes": {
        "type": "revcult__Security_Insights_Refresh__c",
        "url": "/services/data/v52.0/sobjects/revcult__Security_Insights_Refresh__c/a0E0U000006SPOlUAO"
      },
      "revcult__Access_Control_Score__c": 10.0,
      "revcult__Data_Loss_Prevention_Score__c": 10.0,
      "revcult__Data_Protection_Score__c": 10.0,
      "revcult__Integration_Score__c": 10.0,
      "revcult__Monitoring_Score__c": 10.0,
      "revcult__RevCult_Score__c": null,
      "revcult__Run_Date__c": "2000-07-10T19:12:12.000+0000",
      "revcult__Scheduled__c": false,
      "revcult__Security_Model_Score__c": 10.0
    }
  ]
}